jobbase/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("checklogin", views.check_login, name="checklogin"),
    path("firstlogin", views.first_login, name="firstlogin"),
    path("profile", views.profile, name="profile"),
    path("create-checkout-session/<str:id>", views.create_checkout_session, name='checkout'),
    path("profileview", views.editProfile, name="profileview"),
    path("mypage", views.mypage, name="mypage"),
    path("webhook", views.webhook, name="webhook"),
    path("postjob", views.postJob, name="postjob"),
    path("mylistings", views.myListings, name="mylistings"),
    path("allposts/<str:what>/<str:where>", views.allPosts, name="allposts"),
    path("deactivate", views.deactivate, name="deactivate"),
    path("edit/<str:id>", views.editPost, name="editpost"),
    path("applicationcvprocess", views.applicationCVProcess, name="applicationcvprocess"),
    path("apply", views.apply, name="apply"),
    path("applicants/<str:id>", views.applicants, name="applicants"),
    path("messageview", views.messageView, name="messageview"),
    path("message", views.message, name="message"),
    path("myjobs", views.myjobs, name="myjobs"),
    path("getprofile", views.fetchProfile, name="getprofile"),
    path("statuscheck", views.statusCheck, name="statuscheck"),
    path("expirycheck", views.expiryCheck, name="expirycheck")
]

recruitment/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("jobbase.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

jobbase/models.py
from django.contrib.auth.models import AbstractUser
from django.core.files.base import ContentFile
from django.db import models


# Model for Users
class User(AbstractUser):
    employer = models.BooleanField(default=False)


# Model for CVs
class CV(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cv = models.FileField(upload_to='cvfolder', default=None)
    active = models.BooleanField(default=False)


# Model for Job seeker profiles
class profileSeeker(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    location = models.CharField(max_length=250)

    def serialize(self):
        return {
            "ID": self.id,
            "name": self.name,
            "location": self.location
        }


# Model for Employer profiles
class profileEmployer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    companyName = models.CharField(max_length=100)
    personName = models.CharField(max_length=50)
    foundationYear = models.IntegerField()
    companySize = models.CharField(max_length=50)
    headquatersLocation = models.CharField(max_length=250)
    website = models.CharField(max_length=150, default='None')
    
    def serialize(self):
        return {
            "ID": self.id,
            "companyName": self.companyName,
            "personName": self.personName,
            "foundationYear": self.foundationYear,
            "companySize": self.companySize,
            "headquatersLocation": self.headquatersLocation,
            "website": self.website
        }


# Model for job Posts
class jobPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    companyName = models.CharField(max_length=100)
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=250)
    positionType = models.CharField(max_length=50) # Hybrid, remote, etc.
    annualy = models.FloatField()
    hourly = models.FloatField()
    employmentType = models.CharField(max_length=50) # Full-time, part-time, etc.
    jobDescription = models.CharField(max_length=8000)
    date = models.DateField()
    expiry = models.DateField()
    website = models.CharField(max_length=150, default='None')

    def serialize(self):
        return {
            "id": self.id,
            "companyName": self.companyName,
            "active": self.active,
            "title": self.title,
            "location": self.location,
            "positionType": self.positionType,
            "annualy": self.annualy,
            "hourly": self.hourly,
            "employmentType": self.employmentType,
            "jobDescription": self.jobDescription,
            "date": self.date,
            "expiry": self.expiry,
            "website": self.website
        }


# Model for Messages
class Message(models.Model):
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name="message_recipients")
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=2000)
    date = models.DateField()
    time = models.TimeField()

    def serialize(self):
        return {
            "recipientName": getName(self.recipient),
            "recipient": self.recipient.username,
            "recipientID": self.recipient.id,
            "senderName": getName(self.sender),
            "senderID": self.sender.id,
            "sender": self.sender.username,
            "message": self.message,
            "date": self.date,
            "time": self.time
        }

def getName(profile):
    if profile.employer:
        profile = profileEmployer.objects.get(user=User.objects.get(username=profile))
        return profile.personName
    else:
        profile = profileSeeker.objects.get(user=User.objects.get(username=profile))
        return profile.name



# Model for My Jobs (saved, applied)
class myJob(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(jobPost, on_delete=models.CASCADE)
    applied = models.BooleanField()
    saved = models.BooleanField()


# Model for Applications
class Applications(models.Model):
    candidate = models.ForeignKey(profileSeeker, on_delete=models.CASCADE)
    jobpost = models.ForeignKey(jobPost, on_delete=models.CASCADE)
    cv = models.ForeignKey(CV, on_delete=models.CASCADE, blank=True, null=True)
    coverLetter = models.CharField(max_length=8000)

    def serialize(self):
        return {
            "candidate": self.candidate.user.id,
            "name": self.candidate.name,
            "location": self.candidate.location,
            "cvUrl": self.cv.cv.url,
            "coverLetter": self.coverLetter,
            "email": self.candidate.user.email,
        }

jobbase/forms.py
from django import forms
from .models import CV

class CVForm(forms.ModelForm):
    """Form for the CV model"""
    class Meta:
        model =  CV
        fields = ('user', 'cv', 'active')

jobbase/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime, timedelta

import json
import stripe
import re
import os

from .models import *

from .forms import CVForm
from recruitment.settings import BASE_DIR


YOUR_DOMAIN = 'https://jobbase.herokuapp.com'
# This is your test secret API key.
stripe.api_key = 'sk_test_51LyumzJDuT7kCtc6Fzg2NCJPRwDpx9mVApdtih5ADgdluK6C1LMr71INGC6G1zzg0IpTaNcUonzQuXkDiWK5nmf7004742kG9K'

# This is your Stripe CLI webhook secret for testing your endpoint locally.
endpoint_secret = 'whsec_xKZAa2VMnqNOpQbMegiFsjx9omxpQUuo'


def index(request):

    if request.method == "POST":
        form = CVForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Get application from DB and append new CV to it
            application = Applications.objects.get(id=int(request.POST['applicationID']))
            application.cv = CV.objects.get(id=form.instance.id)
            application.save()

    else:
        form = CVForm()

    return render(request, "jobbase/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "jobbase/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "jobbase/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        status = request.POST["status"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "jobbase/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            if status == 'Employer':
                user = User.objects.create_user(username, email, password, employer=True)
                user.save()
            else:
                user = User.objects.create_user(username, email, password)
                user.save()
        except IntegrityError:
            return render(request, "jobbase/register.html", {
                "message": "This username has been already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "jobbase/register.html")


def check_login(request):

    username = False
    signed_in = False
    if request.user.is_authenticated:
        signed_in = True
        username = request.user.username

    return JsonResponse([signed_in, username], safe=False)
 
def first_login(request):

    if request.user.is_authenticated:
        # Create bool to pass in whether the user is an employer or job seeker
        employer = False 

        # Check if the user has a profile
        user = User.objects.get(username=request.user.username)
        
        if not user.employer:
            # Check for an existing profile
            profile = profileSeeker.objects.filter(user=user)
            return JsonResponse([len(profile), employer], safe=False)
        else:
            employer = True
            profile = profileEmployer.objects.filter(user=user)
            return JsonResponse([len(profile), employer], safe=False)

@login_required
def profile(request):

    # Get current user
    user = User.objects.get(username=request.user.username)

    if request.method == "POST":
        # Get data
        data = json.loads(request.body)

        if data['employer'] == True:
            # Create new Profiel and save
            newProfile = profileEmployer(
                user=user, companyName=data['companyName'], personName=data['personName'], 
                foundationYear=data['foundationYear'], companySize=data['companySize'], 
                headquatersLocation=data['headquatersLocation'], website=data['website']
                )

            newProfile.save()
        
        else:

            newProfile = profileSeeker(user=user, name=data['name'], location=data['location'])
            newProfile.save()

        return HttpResponse(status=200)

    if request.method == "GET":

        # Set Bool for validation
        employer = False

        # Validate if current user is an employer or job seeker
        if user.employer:
            employer = True

        return JsonResponse(employer, safe=False)

    if request.method == "PUT":
    
        # Get data
        data = json.loads(request.body)

        if data['employer'] == True and user.employer == True:
            # Get profile
            profile = profileEmployer.objects.get(user=user)

            # Change Profile data and save
            profile.companyName = data['companyName']
            profile.personName = data['personName']
            profile.foundationYear = data['foundationYear']
            profile.companySize = data['companySize']
            profile.headquatersLocation = data['headquatersLocation']
            profile.website = data['website']

            profile.save()

            return HttpResponse(status=200)

        else:
            # Get profile
            profile = profileSeeker.objects.get(user=user)

            profile.name = data['name'] 
            profile.location = data['location'] 

            profile.save()

            return HttpResponse(status=200)


@login_required
def fetchProfile(request):
    
    # Check if user is authenticated and an employer then return profile data
    try:
        if request.user.is_authenticated and request.user.employer:
            profile = profileEmployer.objects.get(user=User.objects.get(username=request.user.username))
            return JsonResponse(profile.serialize(), safe=False)
        
        elif request.user.is_authenticated:
            profile = profileSeeker.objects.get(user=User.objects.get(username=request.user.username))
            return JsonResponse(profile.serialize(), safe=False)
        
        else:
            return HttpResponse(status=404)
    
    except:
        ValueError

    return(HttpResponse(status=401))

def statusCheck(request):
    
    # Check if user is logged in as Employer, Jobseeker or NOT logged in
    if request.user.is_authenticated and request.user.employer:
        responseDic = {'employer': True}
        print('TRUE')
        return JsonResponse(responseDic, safe=False)
    elif request.user.is_authenticated:
        responseDic = {'employer': False}
        print('FALSE')
        return JsonResponse(responseDic, safe=False)
    else:
        responseDic = {'employer': 'None'}
        print('NONE')
        return JsonResponse(responseDic, safe=False)



@login_required
def apply(request):

    # Get current user
    user = User.objects.get(username=request.user.username)

    if request.method == "GET":
        profile = profileSeeker.objects.get(user=user)
        profile = profile.serialize()
        profile['email'] = user.email
        return JsonResponse(profile, safe=False)

    if request.method == "POST":
        # Get data from post request
        data = json.loads(request.body)

        # Get user profile, the job Post
        profile = profileSeeker.objects.get(user=user)
        post = jobPost.objects.get(id=int(data['postID']))

        # Check if the user already applied for this job
        if (len(Applications.objects.filter(candidate=profile, jobpost=post)) != 0):
            return HttpResponse(status=400)

        if data['cvID'] != 'None':
 
            cv = CV.objects.get(id=data['cvID'])
            # Create application object
            new = Applications(candidate=profile, jobpost=post, coverLetter=data['coverLetter'], cv=cv)
            new.save()
            return HttpResponse(status=200)

        else:
            # Create application object
            new = Applications(candidate=profile, jobpost=post, coverLetter=data['coverLetter'])
            new.save()

            return JsonResponse(new.id, safe=False)

        


@login_required
def create_checkout_session(request, id):

    # Get current user
    user = User.objects.get(username=request.user.username)
    if len(jobPost.objects.filter(id=id, user=user)) == 0:
        return HttpResponse(status=401)

    else:
        checkout_session = stripe.checkout.Session.create(
            line_items=[
                {
                    # Provide the exact Price ID (for example, pr_1234) of the product you want to sell
                    'price': 'price_1MIL9AJDuT7kCtc6Civuh4IN',
                    'quantity': 1,
                },
            ],
            mode='payment',
            client_reference_id = id,
            success_url=YOUR_DOMAIN + '/mypage',
            cancel_url=YOUR_DOMAIN + '/mypage',
        )

        return redirect(checkout_session.url, code=303)


@login_required
def editProfile(request):

    # Get current user
    user = User.objects.get(username=request.user.username)

    # Get CV if there is one
    cv = CV.objects.filter(user=user, active=True)
    hasActiveCV = False
    if len(cv) != 0:

jobbase/templates/jobbase/index.html
{% extends "jobbase/layout.html" %}
{% load static %}

{% block body %}

    <div class="container-fluid p-5 mt-4 shadow-sm" id="searchBarContainer">
        <div class="row m-4">
            <div class="col-lg-4 offset-lg-2">
                <label for="whatInput" class="form-label searchBarLabel"><h6>What ?</h6></label>
                <input id="whatInput" type="text" class="form-control" placeholder="Enter your profession" required>
            </div>
            <div class="col-lg-4" id="searchInputDiv"> 
                <label for="autocomplete" class="form-label searchBarLabel"><h6>Where ?</h6></label>
                <input id="autocompletePlaceholder" type="text" class="form-control" placeholder="Enter a location" required>
            </div>
  
            <div class="col-lg-1">
                <button class="btn btn-light p-3 mt-4 container-fluid" id="findJobsBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#00649A" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <div class="container mt-5 p-5" id="main">
    </div>

    <div class="container" id="SeekerModal">
        <button class="btn btn-primary d-none" data-bs-toggle="modal" data-bs-target="#modal2" id="SmodelButton">Open</button> 
        <div class="modal fade" id="modal2" data-bs-backdrop="static" data-bs-keyboard="false">
            <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3>Profile</h3>
                    </div>
                    <div class="modal-body" id="modelBody">
                        <form id="createProfileForm">
                            <div class="container">
                                <label for="firstName" class="form-label">First name</label>
                                <input type="text" id="firstName" class="form-control" required>
                            </div>
                            <div class="container mt-3">
                                <label for="lastName" class="form-label">Last name</label>
                                <input type="text" id="lastName" class="form-control" required>
                            </div>
                            <div class="container mt-3">
                                <label for="autocomplete" class="form-label" id="autocompleteLabel">My location</label>
                                <input type="text" id="autocomplete" class="form-control">
                            </div>
                        </form>
                        <div class="modal-footer mt-5">
                            <button class="btn btn-primary" form="createProfileForm" type="submit" id="formSubmitbtn">Submit</button>
                            <button class="class btn btn-primary d-none" data-bs-dismiss="modal" id="dismissModal"></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <button class="btn btn-primary d-none" data-bs-toggle="modal" data-bs-target="#modal4" id="applyModaBtn">Open</button> 
        <div class="modal fade" id="modal4">
            <div class="modal-dialog modal-xl modal-fullscreen-md-down modal-dialog-centered modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header shadow-sm">
                        <div class="container mt-2 p-4">
                            <h3 id="applyModalHeader"></h3>
                            <h4 id="applyModalCompany"></h4>
                        </div>
                    </div>
                    <div class="modal-body" id="applyModalBody">
                        <div class="container mt-3 p-5" id="applyModalDetails">
                        </div>
                        <div class="container m-2 p-5" id="applyModalJDescription">
                        </div>
                        <div class="div px-4" id="applyAllContent">
                            <div class="container mt-5 px-4">
                                <input type="text" class="form-control disabled" id="namefieldDisabled" readonly>
                            </div>
                            <div class="container mt-3 px-4">
                                <input type="text" class="form-control disabled" id="locationDisabled" readonly>
                            </div>
                            <div class="container mt-3 px-4">
                                <input type="text" class="form-control" id="emailFieldDisabled" readonly>
                            </div>
                            <div class="container mt-5 ms-1 px-4" id="cvBtnGroup">
                                <div class="btn-group btn-group-sm" id="cvBtnGroupContainer">
                                    <a class="btn btn-outline-primary" target="_blank" rel="noopener noreferrer" href="#" id="myCV" data-bs-toggle="tooltip" data-bs-title="View CV">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-file-earmark-text-fill" viewBox="0 0 16 16">
                                            <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM4.5 9a.5.5 0 0 1 0-1h7a.5.5 0 0 1 0 1h-7zM4 10.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 1 0-1h4a.5.5 0 0 1 0 1h-4z"/>
                                        </svg>
                                    </a>
                                    <a class="btn btn-success ms-1" href="#" id="anotherCVBtn">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-upload mb-1" viewBox="0 0 16 16" data-bs-toggle="tooltip" data-bs-title="Upload another">
                                            <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                                            <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/>
                                        </svg>
                                    </a>
                                </div>
                            </div>
                            <form method="post" enctype="multipart/form-data" id="uploadCVForm" class="d-none">
                                {% csrf_token %}
                                <div>
                                    <label for="cv_file">Upload CV</label>
                                    <input type="file" name="cv" accept=".pdf" id="id_cv">
                                    <input type="checkbox" name="active" id="id_active" class="d-none">
                                    <input type="number" name="applicationID" id="applicationID">
                                    <select name="user" class="d-none" required id="id_user">
                                        <option value="{{user.id}}"></option>
                                    </select>
                                </div>
                                <button type="submit">SubmitBtn</button>
                            </form>
                            <div class="container py-3 px-4">
                                <span id="fileName">No CV uploaded.</span>
                            </div>
                            <div class="container mt-5">
                                <div class="accordion" id="coverLetterAccordion">
                                    <div class="accordion-item">
                                      <h2 class="accordion-header" id="headingOne">
                                        <button class="accordion-button bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                            <span class="text-primary">Provide a cover letter (optional)</span>
                                        </button>
                                      </h2>
                                      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#coverLetterAccordion">
                                        <div class="accordion-body p-4">
                                            <textarea id="coverLetter" class="form-control" rows="10" placeholder="Provide a cover letter..."></textarea>
                                        </div>
                                      </div>
                                    </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer border-0 mt-2 p-5" id="applyModalFooter">
                        <button class="btn btn-primary me-3 d-none" data-bs-dismiss="modal" id="closeApplyModal"></button>
                        <button class="btn btn-primary me-3" id="applyJobBtn">Apply</button>  
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container" id="mobileJobModal">
        <button class="btn btn-primary d-none" data-bs-toggle="modal" data-bs-target="#modal10" id="openModal10">Open</button> 
            <div class="modal fade" id="modal10">
                <div class="modal-dialog modal-fullscreen">
                    <div class="modal-content">
                        <div class="modal-body mt-5 text-center pt-5">
                            <img class="mb-2" src="{% static 'jobbase/images/JoBaseModalIcon.svg' %}">
                            <div id="postContentBoxMobile">
                                <div id="postFocusDivMobile">
                                    <h4 id="list-item-1Mobile">Position</h4>
                                    <div id="positionDivMobile">
                                        <p>This is some placeholder content for the scrollspy page. Note that as you scroll down the page, the appropriate navigation link is highlighted. It's repeated throughout the component example. We keep adding some more example copy here to emphasize the scrolling and highlighting.</p>
                                    </div>
                                    <h4 id="list-item-2Mobile" class="mt-5">Job Details</h4>
                                    <div id="jobDetailsDivMobile">
                                        <p>This is some placeholder content for the scrollspy page. Note that as you scroll down the page, the appropriate navigation link is highlighted. It's repeated throughout the component example. We keep adding some more example copy here to emphasize the scrolling and highlighting.</p>
                                    </div>
                                    <h4 id="list-item-3Mobile" class="mt-5">Job Description</h4>
                                    <div id="jobDescriptionDivMobile" class="px-3">
                                        <p>This is some placeholder content for the scrollspy page. Note that as you scroll down the page, the appropriate navigation link is highlighted. It's repeated throughout the component example. We keep adding some more example copy here to emphasize the scrolling and highlighting.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Close</button> 
                        </div>
                    </div>
                </div>
            </div>
    </div>

{% endblock %}

jobbase/templates/jobbase/login.html
{% extends "jobbase/layout.html" %}
{% load static %}

{% block body %}
    {% if message %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endif %}
    <div class="container-fluid py-5 text-center">
        <img src="{% static 'jobbase/images/JoBase.svg' %}">
    </div>

    <div class="container-fluid col-8 col-lg-3 text-center">
        <h2 class="header pb-3" style="color: #00649A;">Welcome back</h2>
        <form id="loginForm" action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input autofocus class="form-control" id="usernameInput" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group mb-3">
                <input autofocus class="form-control d-none" id="passwordInput" type="password" name="password" placeholder="Password">
            </div>
            <input type="button" class="btn btn-primary" id="continueBtn" value="Continue">
        </form>
    
        Don't have an account? <a href="{% url 'register' %}">Register here.</a>
    </div>
{% endblock %}